name = "timeros"
compatibility_date = "2024-01-01"

[build.environment]
NODE_VERSION = "18"

[[build.functions]]
pattern = "/api/*"
allowed_methods = ["GET", "POST", "PUT", "DELETE"]

[functions]
node_compat = true 